### ISSUE TITLE
Where does this part of 'run without docker' refer to the path?

### ISSUE THREAD

**Issue by SungJun9212** [cBioPortal/session-service#32]
Where does this part of 'run without docker' refer to the path?

![image](https://user-images.githubusercontent.com/31676950/88140088-0273eb00-cc2c-11ea-9bfe-90ffe844c66a.png)

**Comment by jjgao** [comment]
answered in https://github.com/cBioPortal/cbioportal/issues/7826

**Comment by tizatt** [comment]
I have this same question - what does /path/to/myapp.config refer to?  I looked at the link above from @jjgao and did not see this question answered in there.

![Screen Shot 2021-01-13 at 11 52 27 AM](https://user-images.githubusercontent.com/20545823/104496233-f2631580-5595-11eb-9787-ddc7d03f7a36.png)
