### ISSUE TITLE
SessionRepositoryImpl.java should not be included in the model dependency jar

### ISSUE THREAD

**Issue by pvannierop** [cBioPortal/session-service#44]
# Problem
Importing the domain/model session service dependency in the Spring Boot version of cBioPortal (work-in-progress) causes an error creating the application context. The cause is that a @MongoTemplate bean used by the [SessionRepositoryImpl.java](/src/main/java/org/cbioportal/session_service/domain/internal/SessionRepositoryImpl.java) is missing.

# Solution
I think that the domain package exported with the `model` classifier (see POM.xml) to the dependency jar incorrectly includes the _SessionRepositoryImpl.java_ class since it contains implementation details, not domain models. I propose to move this class to a different package so that it is not exported into the dependency jar. This will remove the need to configure the Spring application context for this dependency.

A proposed change is available in #45

**Comment by inodb** [comment]
Re-opening this as we reverted it in #50
