### ISSUE TITLE
Upgrade to Java 11

### ISSUE THREAD

**Issue by inodb** [cBioPortal/session-service#46]
For some reason the upgrade to 11 was not seamless: https://github.com/cBioPortal/session-service/commit/39919d7183c7530f2c6ca097a5ad3fb357e9a42b. Couldn't get it to work locally. Some java class error

**Comment by pvannierop** [comment]
@inodb This issue can be closed, right? We are on Java 11.

**Comment by inodb** [comment]
Yup - thanks!
